url: gavingym.github.io
baseurl: 

# Site settings
title: 高光谱云盘-在线解混
email: gavin-gym@foxmail.com
description: "高光谱云盘-在线解混-介绍页."


# Team names, titles and social links
people:


- name: 
  position: 
      
- name: 郭亦铭(GavinGYM)
  pic: 1
  position: Developer & Designer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: github
      url: http://github.com/gavingym

- name: 
  position: 


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: 
  - title: facebook
    url:
  - title: stack-overflow
    url: 
  - title: bitbucket 
    url: 
  - title: github
    url: http://github.com/gavingym

# Postal address (add as many lines as necessary)
address:
  - line: 上海市松江区
  - line: 人民北路2999号东华大学, 201620

# Build settings
markdown: kramdown
permalink: pretty
